achievement_lookup = {
   1: "first_day",
   2: "first_drink",
   3: "first_sleep",
   4: "first_steps",
   5: "first_workout",
   6: "new_profile",
   7: "ten_exercises",
   8: "rep_warrior",
   9: "set_it_off",
   10: "sleep_maxxed",
   11: "heavy_lifter_I",
   12: "heavy_lifter_II",
   13: "step_stacker_I",
   14: "step_stacker_II",
   15: "hydrated_human_I",
   16: "hydrated_human_II",
   17: "sleeping_beauty_I",
   18: "sleeping_beauty_II",
   19: "1_month_club"
}