achievement_lookup = {
   1: ["first_day", "First Day"],
   2: ["first_drink", "First Drink"],
   3: ["first_sleep", "First Sleep"],
   4: ["first_steps", "First Steps"],
   5: ["first_workout", "First Workout"],
   6: ["new_profile", "New Profile"],
   7: ["ten_exercises", "Ten Exercises"],
   8: ["rep_warrior", "Rep Warrior"],
   9: ["set_it_off", "Set It Off"],
   10: ["sleep_maxxed", "Sleep Maxxed"],
   11: ["heavy_lifter_I", "Heavy Lifter I"],
   12: ["heavy_lifter_II", "Heavy Lifter II"],
   13: ["step_stacker_I", "Step Stacker I"],
   14: ["step_stacker_II", "Step Stacker II"],
   15: ["hydrated_human_I", "Hydrated Human I"],
   16: ["hydrated_human_II", "Hydrated Human"],
   17: ["sleeping_beauty_I", "Sleeping Beauty I"],
   18: ["sleeping_beauty_II", "Sleeping Beauty II"],
   19: ["1_month_club", "1 Month Club"]
}