import customtkinter as ctk
from PIL import Image

achievements_triple_stars = ctk.CTkImage(light_image=Image.open("img/achievements/original_icons/triple_stars.png"), dark_image=Image.open("img/achievements/original_icons/triple_stars.png"), size=(128, 96))
achievements_banner = ctk.CTkImage(light_image=Image.open("img/achievements/original_icons/achievement_banner.png"), dark_image=Image.open("img/achievements/original_icons/achievement_banner.png"), size=(96, 96))

locked_locked_achievement_1_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_2_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96)) 
locked_achievement_3_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_4_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_5_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_6_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_7_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_8_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_9_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_10_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_11_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_12_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_13_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_14_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_15_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_16_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_17_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_18_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
locked_achievement_19_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))

unlocked_achievement_1_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_2_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96)) 
unlocked_achievement_3_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_4_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_5_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_6_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_7_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_8_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_9_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_10_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_11_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_12_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_13_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_14_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_15_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_16_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_17_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_18_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))
unlocked_achievement_19_icon = ctk.CTkImage(light_image=Image.open("img/achievements/unlocked_version/first_day.png"), dark_image=Image.open("img/achievements/unlocked_version/first_day.png"), size=(96, 96))