import customtkinter as ctk
from PIL import Image

achievements_triple_stars = ctk.CTkImage(light_image=Image.open("img/achievements/original_icons/triple_stars.png"), dark_image=Image.open("img/achievements/original_icons/triple_stars.png"), size=(128, 96))
achievements_banner = ctk.CTkImage(light_image=Image.open("img/achievements/original_icons/achievement_banner.png"), dark_image=Image.open("img/achievements/original_icons/achievement_banner.png"), size=(96, 96))
achievement_1_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_2_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96)) 
achievement_3_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_4_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_5_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_6_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_7_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_8_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_9_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_10_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_11_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_12_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_13_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_14_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_15_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_16_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_17_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_18_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
achievement_19_icon = ctk.CTkImage(light_image=Image.open("img/achievements/locked_version/first_day.png"), dark_image=Image.open("img/achievements/locked_version/first_day.png"), size=(96, 96))
